package Entity;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BLOOD_PRE".
*/
public class BloodPreDao extends AbstractDao<BloodPre, Long> {

    public static final String TABLENAME = "BLOOD_PRE";

    /**
     * Properties of entity BloodPre.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property Shousuo = new Property(1, String.class, "shousuo", false, "SHOUSUO");
        public final static Property Shuzhang = new Property(2, String.class, "shuzhang", false, "SHUZHANG");
        public final static Property User = new Property(3, String.class, "user", false, "USER");
        public final static Property Time = new Property(4, Long.class, "time", false, "TIME");
    }


    public BloodPreDao(DaoConfig config) {
        super(config);
    }
    
    public BloodPreDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BLOOD_PRE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"SHOUSUO\" TEXT," + // 1: shousuo
                "\"SHUZHANG\" TEXT," + // 2: shuzhang
                "\"USER\" TEXT," + // 3: user
                "\"TIME\" INTEGER);"); // 4: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BLOOD_PRE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BloodPre entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String shousuo = entity.getShousuo();
        if (shousuo != null) {
            stmt.bindString(2, shousuo);
        }
 
        String shuzhang = entity.getShuzhang();
        if (shuzhang != null) {
            stmt.bindString(3, shuzhang);
        }
 
        String user = entity.getUser();
        if (user != null) {
            stmt.bindString(4, user);
        }
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(5, time);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BloodPre entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String shousuo = entity.getShousuo();
        if (shousuo != null) {
            stmt.bindString(2, shousuo);
        }
 
        String shuzhang = entity.getShuzhang();
        if (shuzhang != null) {
            stmt.bindString(3, shuzhang);
        }
 
        String user = entity.getUser();
        if (user != null) {
            stmt.bindString(4, user);
        }
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(5, time);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BloodPre readEntity(Cursor cursor, int offset) {
        BloodPre entity = new BloodPre( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // shousuo
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // shuzhang
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // user
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BloodPre entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setShousuo(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setShuzhang(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUser(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTime(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BloodPre entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BloodPre entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BloodPre entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
